USE skinsite;

INSERT INTO Concern (concernName, concernDetail) VALUES
  ('Paraben Free',"No parabens synthetic preservatives are present"),
  ('Alcohol Free','Contains no drying alcohols like ethanol or isopropyl alcohol.'),
  ('Fragrance Free','No synthetic or natural fragrances are included.'),
  ('Cruelty Free','Depends on the brand''s certifications; ingredients themselves do not indicate testing on animals.'),
  ('Silicone Free','Contains Cyclopentasiloxane, a type of silicone.'),
  ('Colorant Free','Contains CI 14700, a synthetic colorant.'),
  ('Vegan','Ingredients are plant-based or synthetic, with no animal derivatives. However, check the brand''s certification.'),
  ('Pregnancy Safe','Most ingredients are safe during pregnancy, but consult a doctor if unsure about Benzophenone-4.'),
  ('Reef Safe','Benzophenone-4 may not be safe for marine ecosystems, as it can harm coral reefs.'),
  ('Petroleum oil-Free','Does not contain petroleum-based oils, which are often heavy and can clog pores or irritate the skin.'),
  ('Steroid-Free','Does not contain steroids, which are sometimes used in skincare but may have potential side effects with prolonged use.'),
  ('Coral-Harming UV Filters-Free*','Free from UV filters that could harm coral reefs, emphasizing environmentally-friendly ingredients that are safe for marine life.'),
  ('Not Tested on Animals','Ensures that products are developed without any animal testing at any stage of production.'),
  ('Mineral Oil Free','Does not contain mineral oils, which can clog pores and hinder skin’s natural ability to breathe.'),
  ('Sulfate Free','Free from sulfates (like SLS and SLES), that can strip moisture from the skin and hair.'),
  ('Polyethylene Free','Does not contain polyethylene, a type of plastic that can contribute to environmental pollution.'),
  ('Free from Other Irritating Substances','Free from ingredients that can cause irritation or adverse reactions, making it suitable for sensitive skin.'),
  ('Microplastic Free','Does not contain microplastics, which are harmful to marine life and the environment.'),
  ('Free from Petroleum','Free from petroleum-based ingredients, which can be heavy and cause skin blockages.'),
  ('Free from Polyethylene','No use of polyethylene, which is a plastic that can harm ecosystems and is often found in scrubs and exfoliants.'),
  ('Free from SLS & Sulphates','Free from Sodium Lauryl Sulfate (SLS), and other sulfates that can irritate and dry out skin and hair.'),
  ('Talc','Does not contain talc, a mineral sometimes linked to contamination concerns and potential skin irritation.'),
  ('No Essential oil','Does not contain essential oils, reducing the risk of irritation.'),
  ('Hydroquinone Free','Does not include hydroquinone, a skin-lightening agent that may cause sensitivity.'),
  ('Phthalates Free','Free from phthalates, chemicals often used in fragrances and plastics, linked to potential health risks.'),
  ('Preservative Free','Does not contain synthetic preservatives that may cause irritation.'),
  ('Phenoxyethanol','A preservative used to prevent microbial growth in cosmetics.'),
  ('PEG/PPG','Lacks polyethylene glycol (PEG), and polypropylene glycol (PPG),, which may cause skin sensitivity or contamination concerns.');
